### POST request to example server
POST http://localhost:8080/saveLikesDislikeAction?selectType=DISLIKE
Content-Type: application/json
Authorization: {{authToken}}

{
  "articleId": 5,
  "createMemberId": 12,
  "type": "LIKE"
}