### Send POST request with json body
POST http://localhost:8080/member
Content-Type: application/json

{
  "username": "maple",
  "email": "vwko1234567@naver.com",
  "password": "123123",
  "introduction": "방랑자입니다",
  "profileImage": "/image"
}