### Send POST request with json body
POST http://localhost:8080/updateMember
Content-Type: application/json
Authorization: {{authToken}}


{
  "id": 6,
  "introduction": "유랑자입니다",
  "profileImageUrl": "/ima"
}